### ISSUE TITLE
ses_bounce_logging_blog.yml Import Error

### ISSUE THREAD

**Issue by rldaulton** [aws-samples/digital-user-engagement-reference-architectures#21]
When following the [blog article](https://aws.amazon.com/blogs/messaging-and-targeting/how-to-log-amazon-ses-details-using-amazon-cloudwatch/) to log bounce SES events in a CloudWatch group, upon reaching the step to deploy a Cloud Formation stack with the supplied YML file, I receive the following error.

> The following resource types are not supported for resource import: AWS::SNS::Subscription

<img width="1884" alt="Screenshot 2023-12-29 at 10 57 27 AM" src="https://github.com/aws-samples/communication-developer-services-reference-architectures/assets/11828603/c10ce72f-a65d-4789-9147-42dea174b87a">

**Comment by bgiorgini** [comment]
Thanks for your contact. The Cloudformation UI changed since the Blog post. 
Please use the standard option to create the stack in Cloudformation instead of the "import resources".

![image](https://github.com/aws-samples/communication-developer-services-reference-architectures/assets/2769856/799a10b6-9b49-4b9c-8247-40b159bb803e)

**Comment by bgiorgini** [comment]
Please reopen this issue if you still have problems deploying the solution.
